/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employees_Details;

import com.sun.glass.events.KeyEvent;
import java.awt.Component;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author saifilali
 */
public class Employee_Details extends javax.swing.JFrame {

    /**
     * Creates new form Employee_Details
     */
    public Employee_Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtFirstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtLastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtEmployeeid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtSalary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtTechnicalskills = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtJoiningdate = new com.toedter.calendar.JDateChooser();
        jcmbDesignation = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtShow = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnClear = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnShow = new javax.swing.JButton();
        jbtnExport = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee_Details");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4), "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("First Name");

        jtxtFirstname.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("Last Name");

        jtxtLastname.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setText("Employee ID");

        jtxtEmployeeid.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jtxtEmployeeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmployeeidActionPerformed(evt);
            }
        });
        jtxtEmployeeid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtEmployeeidKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Salary");

        jtxtSalary.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jtxtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSalaryActionPerformed(evt);
            }
        });
        jtxtSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtSalaryKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setText("Designation");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setText("Technical Skills");

        jtxtTechnicalskills.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel7.setText("Joining Date");

        jtxtJoiningdate.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        jcmbDesignation.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jcmbDesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Designation", "Chief Executive Officer", "Associate", "Senior Associate", "Account Executive", "Administrative Assistant", "Administrative Manager", "Branch Manager", "Business Analyst", "Business Manager", "Office Manager", "Operations Manager", "Quality Control Coordinator", "Risk Manager", "Service Representative" }));
        jcmbDesignation.setMaximumSize(new java.awt.Dimension(32767, 42767));
        jcmbDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbDesignationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtSalary)
                    .addComponent(jtxtTechnicalskills)
                    .addComponent(jtxtEmployeeid)
                    .addComponent(jtxtFirstname)
                    .addComponent(jtxtLastname)
                    .addComponent(jtxtJoiningdate, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jcmbDesignation, 0, 1, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtEmployeeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtxtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcmbDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jtxtTechnicalskills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jtxtJoiningdate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 530, 410));
        jPanel1.getAccessibleContext().setAccessibleName("Employee Entry");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4), "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 24)), "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 24))); // NOI18N

        jtxtShow.setColumns(20);
        jtxtShow.setRows(5);
        jScrollPane1.setViewportView(jtxtShow);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 430, 410));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "First Name", "Last Name", "Salary", "Designation", "Technical Skills", "Joining Date"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 1090, 140));

        jbtnClear.setBackground(new java.awt.Color(153, 153, 153));
        jbtnClear.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jbtnClear.setText("Clear");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 580, -1, -1));

        jbtnAdd.setBackground(new java.awt.Color(0, 153, 51));
        jbtnAdd.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jbtnAdd.setText("Add");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, -1, -1));

        jbtnShow.setBackground(new java.awt.Color(0, 102, 204));
        jbtnShow.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jbtnShow.setText("Show");
        jbtnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, -1, -1));

        jbtnExport.setBackground(new java.awt.Color(153, 153, 0));
        jbtnExport.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jbtnExport.setText("Export");
        jbtnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExportActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 150, -1));

        jbtnDelete.setBackground(new java.awt.Color(255, 0, 51));
        jbtnDelete.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jbtnExit.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 120, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        
        JTextField temp=null;
        
        for(Component c:jPanel1.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                temp=(JTextField)c;
                temp.setText(null);
            }
        }
        jcmbDesignation.setSelectedIndex(0);
        jtxtJoiningdate.setDate(null);
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
            
            jtxtEmployeeid.getText(),
            jtxtFirstname.getText(),
            jtxtLastname.getText(),
            jtxtSalary.getText(),
            jcmbDesignation.getSelectedItem(),
            jtxtTechnicalskills.getText(),
            jtxtJoiningdate.getDate().toString()
            
        });
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowActionPerformed
        jtxtShow.append("=====================================\n"
                + "\n\t      EMPLOYEE DETAILS \n" 
                + "=====================================\n" 
                + "\n\n  First Name:\t\t" + jtxtFirstname.getText()
                + "\n\n  Last Name:\t\t" + jtxtLastname.getText()  
                + "\n\n  Employee ID:\t\t" + jtxtEmployeeid.getText()
                + "\n\n  Salary:\t\t$" + jtxtSalary.getText()
                + "\n\n  Designation:\t\t" + jcmbDesignation.getSelectedItem()
                + "\n\n  Techinical Skills:\t" + jtxtTechnicalskills.getText()
                + "\n\n  Joining Date:\t\t" + jtxtJoiningdate.getDate().toString()
                + "\n\n\n"
                );
    }//GEN-LAST:event_jbtnShowActionPerformed
    
    private JFrame frame1;
    private void jbtnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExportActionPerformed
      
        frame1 = new JFrame("Export");
        if(JOptionPane.showConfirmDialog(frame1, "Do you want to export all your data to a file?", "Employee Database System", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
           DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
            try{
            File file = new File("/Users/saifilali/Desktop/JPMC/database.txt ");
           if(!file.exists()){
               file.createNewFile();
           }
           
           FileWriter fw = new FileWriter(file.getAbsoluteFile());
           BufferedWriter bw = new BufferedWriter(fw);
           bw.write("EmployeeID  |   FirstName  |   LastName  |  Salary  |  Designation  |  TechnicalSkills  |  Joining Date  |\n");
           for(int i = 0; i < jTable1.getRowCount(); i++){
               for(int j = 0; j < jTable1.getColumnCount(); j++){
                   
                   bw.write((String)jTable1.getModel().getValueAt(i,j)+" ");
                   bw.write("   |   ");
               }
               bw.write("\n\n");
           }
           bw.close();
           fw.close();
           JOptionPane.showMessageDialog(null,"Data Exported. Check JPMC folder");
           
          }catch(Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbtnExportActionPerformed

    private void jtxtSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSalaryKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE)
            ||(iNumber == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtSalaryKeyTyped

    private void jtxtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSalaryActionPerformed

    private void jtxtEmployeeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmployeeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmployeeidActionPerformed

    private void jtxtEmployeeidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmployeeidKeyTyped
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACKSPACE)
            ||(iNumber == KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtEmployeeidKeyTyped

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                
                JOptionPane.showMessageDialog(null,"No data to delete", "Employee Database System", JOptionPane.OK_OPTION);
            }
            else{
               JOptionPane.showMessageDialog(null,"Select a row from below to delete", "Employee Database System", JOptionPane.OK_OPTION); 
            }
        }
        else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Employee Database System", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jcmbDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbDesignationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel"); 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnExport;
    private javax.swing.JButton jbtnShow;
    private javax.swing.JComboBox<String> jcmbDesignation;
    private javax.swing.JTextField jtxtEmployeeid;
    private javax.swing.JTextField jtxtFirstname;
    private com.toedter.calendar.JDateChooser jtxtJoiningdate;
    private javax.swing.JTextField jtxtLastname;
    private javax.swing.JTextField jtxtSalary;
    private javax.swing.JTextArea jtxtShow;
    private javax.swing.JTextField jtxtTechnicalskills;
    // End of variables declaration//GEN-END:variables
}
